Repository renproject/hyperdrive, pull requests merged in 2020-03, with the labels that each got.

#38 Restart process timer on boot
  .circleci/config.yml
  process/process.go
  process/process_test.go
  testutil/process.go
Labels: bug

#40 Send Resync message on boot to catch up with peers
  hyperdrive_test.go
  process/marshal.go
  process/marshal_test.go
  process/message.go
  process/message_test.go
  process/process.go
  process/process_test.go
  replica/broadcast.go
  replica/broadcast_test.go
  replica/marshal.go
  replica/marshal_test.go
  replica/rebase_test.go
  replica/replica_test.go
  testutil/process.go
  testutil/replica/replica.go
  testutil/replica/storage.go
Labels: enhancement

#43 Resend our prevote for the locked round inside a propose
  process/process.go
  process/process_test.go
Labels: bug, enhancement

#42 Application binary interface security fixes
  block/block.go
  block/block_test.go
  block/marshal.go
  go.mod
  go.sum
  hyperdrive_test.go
  process/marshal.go
  process/marshal_test.go
  process/message.go
  process/message_test.go
  process/process.go
  process/process_test.go
  process/state.go
  process/state_test.go
  replica/marshal.go
  replica/marshal_test.go
  replica/rebase.go
  replica/replica.go
  replica/replica_test.go
  testutil/block.go
  testutil/process.go
  testutil/replica/replica.go
  testutil/replica/storage.go
Labels: bug, enhancement

#45 Delegate saving/restoring state to process
  go.mod
  process/process.go
  replica/replica.go
  replica/replica_suite_test.go
  testutil/process.go
  testutil/replica/replica.go
  testutil/replica/storage.go
Labels: bug, enhancement

#65 Check propose schedule before insert propose
  go.mod
  process/process.go
  process/process_test.go
  replica/replica_test.go
Labels: bug

#67 Ignore duplicate messages
  process/message.go
Labels: bug, enhancement, good first issue

#56 Fix checking of propose with prevotes for the first time
  process/process.go
  process/process_test.go
Labels: bug

#71 Implement message queue
  process/process.go
  replica/mq.go
  replica/mq_test.go
  replica/replica.go
Labels: enhancement

#74 Fix/hash using surge
  block/block.go
  process/marshal.go
  process/message.go
  replica/rebase.go
  replica/replica.go
Labels: bug, good first issue

#75 Define stand-alone scheduling package
  hyperdrive.go
  process/process.go
  replica/replica.go
  replica/replica_test.go
  replica/schedule.go
  replica/schedule_test.go
  schedule/schedule.go
  schedule/schedule_suite_test.go
  schedule/schedule_test.go
  testutil/process.go
Labels: enhancement, good first issue

#60 Restrict number of latest precommits
  process/message.go
  process/process.go
Labels: bug

#76 Bad behaviour catcher
  hyperdrive.go
  process/catch.go
  process/catch_test.go
  process/message.go
  process/message_test.go
  process/process.go
  replica/rebase.go
  replica/replica.go
  replica/replica_test.go
  testutil/process.go
Labels: enhancement, good first issue
